baseURL = "https://fujiangwei.github.io/"
languageCode = "zh-CN"
title = "来学吧 | 猿有道"
theme = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "docs"


[params]
    author        = "fujiangwei"
    description   = "来学吧 | 猿有道"
    siteurl       = "https://fujiangwei.github.io/"
    about         = "./about"   # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com"
    enablePreLoad = false		    		        # 网站完全打开前预加载的动画
    textPreLoad   = "来学吧 | 猿有道"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    logosPath     = "assets/images/logos"				# 网站每个导航地址logo存放地址
    # 开启访问量统计
    busuanzi = "true"

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/search-bg-light.png"		#搜索部分浅色背景图
    searchImageD      = "assets/images/search-bg-dark.png"		#搜索部分深色背景图
    logoExpandLight   = "assets/images/lxb-expand-light.png"
    logoExpandDark    = "assets/images/lxb-expand-dark.png"
    logoCollapseLight = "assets/images/lxb-collapse-light.png"
    logoCollapseDark  = "assets/images/lxb-collapse-dark.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：2444179219@qq.com <br/>&copy; 2021 - {year} By [来学吧 | 猿有道](https://fujiangwei.github.io/) <br/>'
